# .github/workflows/docker-build-app-service.yml

name: Build & Push app-service

on:
  push:
    paths:
      - 'app/app-service/**'
      - '.github/workflows/docker-build-app-service.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # === THIS IS THE STEP I NEED THE OUTPUT FROM ===
    - name: List files in the repository
      run: ls -laR

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push app-service image
      uses: docker/build-push-action@v5
      with:
        # The context is now the directory containing the code and Dockerfile
        context: ./app/app-service
        
        # The file path is still relative to the repo root
        file: ./app/app-service/Dockerfile
        
        push: true
        
        tags: ghcr.io/remla25-team11/app-backend:latest