# .github/workflows/docker-build-app-service.yml

name: Build & Push app-service

on:
  push:
    # This path is correct for your structure
    paths:
      - 'app/app-service/**'
      - '.github/workflows/docker-build-app-service.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }} # Ensure this is correctly set in repo secrets

    - name: Build and push app-service image
      uses: docker/build-push-action@v5
      with:
        # The context for the build is the repository root directory.
        context: .
        
        # The path to the Dockerfile is relative to the repository root.
        file: ./app/app-service/Dockerfile
        
        push: true
        
        # IMPORTANT: The image name here MUST match what your Helm chart expects.
        # Your Helm chart's values.yaml uses 'app-backend' for the repository name.
        tags: ghcr.io/remla25-team11/app-backend:latest
