# .github/workflows/docker-build-app-service.yml

name: Build & Push app-service

on:
  push:
    paths:
      # Correct path to your application code
      - 'app/app-service/**'
      - '.github/workflows/docker-build-app-service.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }} # Ensure GH_TOKEN is set in your repo secrets

    - name: Build and push app-service image
      uses: docker/build-push-action@v5
      with:
        # The context is the root of the repository
        context: .
        # The Dockerfile is at this specific path
        file: ./app/app-service/Dockerfile
        push: true
        # The image name should match your Helm chart
        tags: ghcr.io/remla25-team11/app-backend:latest
