name: Build & Push app-service

on:
  push:
    paths:
      - 'app-service/**'
      - '.github/workflows/docker-build-app-service.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push app-service image
      uses: docker/build-push-action@v5
      with:
        context: ./app-service
        file: ./app-service/Dockerfile
        push: true
        tags: ghcr.io/remla25-team11/app-service:latest
