name: Release to GHCR

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Parse version info from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=$(echo "$VERSION" | cut -d . -f 1 | tr -d 'v')
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker images
        run: |
          IMG="ghcr.io/${{ github.repository }}"
          IMG=${IMG@L}  # make repo name lowercase
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .
          docker push $IMG:${{ env.version }}
          docker push $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest
          docker push $IMG:${{ env.version_major }}.latest
          docker push $IMG:latest

      - name: Create tag in lib-version repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Install GitHub CLI
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+rw /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

          # Fetch the latest commit SHA from lib-version repository's main branch
          LIB_VERSION_SHA=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/remla25-team11/lib-version/git/refs/heads/main \
            --jq '.object.sha')
          echo "Latest lib-version SHA: $LIB_VERSION_SHA"

          # Create tag in lib-version repository
          # Ensure GH_TOKEN has write access to lib-version repository
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/remla25-team11/lib-version/git/refs \
            -F ref="refs/tags/${{ env.version }}" \
            -F sha="$LIB_VERSION_SHA"
